apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: ndhlovu/auth
      context: auth-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "server/**/*.ts"
            dest: .

    - image: ndhlovu/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .

    - image: ndhlovu/boards
      context: boards-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "server/**/*.ts"
            dest: .
