apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
      - ./infra/k8s-dev/*
build:
  local:
    push: false
  artifacts:
    - image: ndhlovu/auth
      context: auth-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'server/**/*.ts'
            dest: .

    - image: ndhlovu/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        infer:
          - 'src/**/*.tsx'
          - 'src/**/*.ts'
          - 'next.config.js'

    - image: ndhlovu/boards
      context: board-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'server/**/*.ts'
            dest: .

    - image: ndhlovu/accounts
      context: accounts-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'server/**/*.ts'
            dest: .

    - image: ndhlovu/payments
      context: payments-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'server/**/*.ts'
            dest: .

    - image: ndhlovu/email
      context: email-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'server/**/*.ts'
            dest: .
