version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-server
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  auth:
    container_name: node-server
    # image: ndhlovu/node-server
    build: .
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      - NODE_ENV=production
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
