version: "3"
services:
  nginx:
    ports:
      - "4000:80"

  auth:
    build:
      context: .
      args:
        NODE_ENV: development

    environment:
      - NODE_ENV=development
      - PORT=4000
    env_file:
      - ./.env

    volumes:
      - ./:/app
      - /app/node_modules

    command: "yarn docker:dev"
