version: "3"
services:
  nginx:
    ports:
      - "80:80"

  auth:
    build:
      context: .
      args:
        NODE_ENV: production
    env_file:
      - ./.env
    command: yarn prod
    ndhlovu
    /
    node-server