apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: ndhlovu/client
          env:
            - name: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
              valueFrom:
                secretKeyRef:
                  name: env-config
                  key: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY

            - name: NEXT_PUBLIC_NGINX_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: env-config
                  key: NEXT_PUBLIC_NGINX_BASE_URL

            - name: NEXT_PUBLIC_SPOTIFY_ID
              valueFrom:
                secretKeyRef:
                  name: env-config
                  key: NEXT_PUBLIC_SPOTIFY_ID

            - name: NEXT_PUBLIC_HOST
              valueFrom:
                secretKeyRef:
                  name: env-config
                  key: NEXT_PUBLIC_HOST

---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000
