apiVersion: apps/v1
kind: Deployment
metadata:
  name: upgrades-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upgrades
  template:
    metadata:
      labels:
        app: upgrades
    spec:
      containers:
        - name: upgrades
          image: ndhlovu/upgrades
          env:
            - name: JWT_TOKEN_SIGNATURE
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_TOKEN_SIGNATURE

            - name: JWT_REFRESH_TOKEN_SIGNATURE
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_REFRESH_TOKEN_SIGNATURE

            - name: UPGRADES_MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-uri
                  key: UPGRADES_MONGO_URI

            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: mongo-port
                  key: PORT

            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            - name: NATS_CLUSTER_ID
              value: board

            - name: NATS_URL
              value: "http:/nats-srv:4222/"
---
apiVersion: v1
kind: Service
metadata:
  name: upgrades-srv
spec:
  selector:
    app: upgrades
  ports:
    - name: upgrades
      protocol: TCP
      port: 3000
      targetPort: 3000
