up: 
	docker-compose -f docker-compose.yml -f docker-compose.dev.yml up


down: 
	docker-compose -f docker-compose.yml -f docker-compose.dev.yml down

# up-prod:
# 	docker-compose -f docker-compose.yaml -f docker-compose.dev.yaml up -d