name: deploy-auth

on: 
  push:
    branches:
      - main
    paths: 
      - 'auth/**'

jobs:
  build:
    runs-on: ubuntu latest
    steps:
      - uses: actions/checkou@v2
      - run: cd auth && docker buiLd -t ndhlovu/auth .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env: 
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push ndhlovu/auth       
          
      
