name: deploy-auth

on:
  push:
    branches:
      - main
    paths:
<<<<<<< HEAD
      - "auth-service/**"
=======
      - "auth/**"
>>>>>>> 5b668748d3633e13453be5d6736915a6a88e6a55

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
<<<<<<< HEAD
          token: ${{ secrets.WORKFLOWS_TOKEN }}
=======
          token: ${{secrets.WORKFLOWS_TOKEN}}
>>>>>>> 5b668748d3633e13453be5d6736915a6a88e6a55
      - run: cd auth-service && docker buiLd -t ndhlovu/auth .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push ndhlovu/auth
