name: deploy-auth

on:
  push:
    branches:
      - main
    paths:
      - "auth-service/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

        with:
          # persist-credentials: false
          token: ${{ secrets.WORKFLOWS_TOKEN }}

      - run: cd auth-service && docker buiLd -t ndhlovu/auth .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push ndhlovu/auth
